apiVersion: v1
kind: Service
metadata:
  name: {{ include "pythonapp.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "pythonapp.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
