apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-password
        ports:
        - containerPort: {{ .Values.mysql.port }}
          name: mysql
