apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  clusterIP: None
